# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job:
    pool:
      name: "Default"
      demands: "gpu"
    displayName: "Build and Test"
    container:
      image: http://pytorch.azurecr.io/tmp-lpmzxocpdogrtxhbleawtkoqukyezwwv:latest
      endpoint: pytorch
    #   image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda9-cudnn7-py3:300
    #   endpoint: aws_docker
    #   options: -u 0 --runtime=nvidia
    timeoutInMinutes: 360
    steps:
    - checkout: self
      submodules: "true"
    - bash: |
        set -x
        sudo chown -R /opt/conda
        # we should probably remove the sudo -E; this is because the container user
        # azure creates is not the same as the docker container owner, and chown -R'ing
        # everything takes a long time.
        .jenkins/pytorch/build.sh
      env:
        BUILD_ENVIRONMENT: pytorch-linux-xenial-cuda9-cudnn7-py3-build
        SCCACHE_BUCKET: "ossci-compiler-cache-circleci-v2"
        AWS_ACCESS_KEY_ID: $(SCCACHE_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(SCCACHE_SECRET)
      displayName: 'Build'
    - bash: |
        set +x
        set -e
        export PATH="/home/suo_azpcontainer/.local/bin:$PATH"
        .jenkins/pytorch/test.sh
      env:
        BUILD_ENVIRONMENT: pytorch-linux-xenial-cuda9-cudnn7-py3-test
        USE_CUDA_DOCKER_RUNTIME: 1
      displayName: 'Test'

# jobs:
#   - job:
#     pool: "Default"
#     displayName: "Build and Test"
#     container:
#       image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-trusty-py3.5:300
#       endpoint: aws_docker
#       options: -u 0
#     timeoutInMinutes: 120
#     steps:
#     - checkout: self
#       submodules: "true"
#     - bash: |
#         set +x
#         sudo chown -R azureuser_azpcontainer:azureuser_azpcontainer /usr/local
#         sudo chown -R azureuser_azpcontainer:azureuser_azpcontainer /opt/python
#         .jenkins/pytorch/build.sh
#       env:
#         BUILD_ENVIRONMENT: pytorch-linux-trusty-py3.5-build
#         SCCACHE_BUCKET: "ossci-compiler-cache-circleci-v2"
#         AWS_ACCESS_KEY_ID: $(SCCACHE_ACCESS_KEY_ID)
#         AWS_SECRET_ACCESS_KEY: $(SCCACHE_SECRET)
#       displayName: 'Build'
#     - bash: |
#         set +x
#         set -e
#         export PATH="/home/azureuser_azpcontainer/.local/bin:$PATH"
#         .jenkins/pytorch/test.sh
#       env:
#         BUILD_ENVIRONMENT: pytorch-linux-trusty-py3.5-test
#       displayName: 'Test'
